# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-18 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170331_0451'),
        ('polls', '0003_transaction_account'),
    ]

    operations = [
    ]
